/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseLoading: typeof import('./components/BaseComponents/BaseLoading.vue')['default']
    BaseNoticeBar: typeof import('./components/BaseComponents/BaseNoticeBar.vue')['default']
    PopBase: typeof import('./components/Popups/PopBase.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
